version: "3.8"
services:
  mysql:
    container_name: "mysql"
    restart: unless-stopped
    hostname: "docker-mysql"
    build:
      context: ./mysql
    ports:
      - "6603:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=nodejs
  nodeserver:
    container_name: "app"
    restart: unless-stopped
    depends_on:
      - mysql
    build:
      context: ./app
    ports:
      - "5000:5000"
  nginx:
    container_name: "nginx"
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"