apiVersion: v1
kind: Pod
metadata:
  name: my-little-pod
spec:
  containers:
    - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80
    - name: redis
        image: redis
        volumemounts:
          - name: redis-storage
              mountPath: /data/redis
  volumes:
    - name: redis-storage
        emptyDir: {}